version: 2
jobs:
  build:
    working_direction: ~/riot-markdown-editor
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn -v

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run: yarn build
  test:
    working_directory: ~/riot-markdown-editor
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install -g yarn
      - run: yarn -v

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run: yarn build
      - run: yarn lint
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
